name: Build and Test (Assembly malloc)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: make

      # Lancia l'eseguibile corretto (si chiama 'malloc', non 'test')
      - name: Run unit test
        run: ./malloc

      # Stress test (evito dipendenze da run.sh)
      - name: Run stress loop
        run: |
          for n in $(seq 1 100); do ./malloc; done
